version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD="${MSSQL_DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=${ORACLE_DB_ROOT_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./data:/opt/oracle/oradata
    networks:
      - oracle_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
      - MYSQL_USER=${MYSQL_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql_network

networks:
  oracle_network:
  mysql_network:
