version: "3.4"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - .docker/mysql/:/var/lib/mysql
       - db
    networks:
      - docker_network
      - public_net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - ${PHPMYADMIN_PORT}:80
      links:
        - mysql
      environment:
          PMA_HOST: mysql
      networks:
        - docker_network
        - public_net

volumes:
  db:
networks:
  docker_network:
    internal: true
  public_net:
    driver: bridge
